/**
 * Edit this file to supply your real 50-person list before running the server.
 * Each entry: { name, title, company }
 */
module.exports = [
  { name: "Sarah Chen",         title: "Chief Technology Officer",       company: "Meridian Financial Group" },
  { name: "Marcus Webb",        title: "VP of Operations",               company: "Apex Global Logistics" },
  { name: "Priya Nair",         title: "Chief Information Officer",      company: "VaultBridge Insurance" },
  { name: "Daniel Okafor",      title: "Head of Digital Transformation", company: "Stratos Telecom" },
  { name: "Elena Vasquez",      title: "SVP Enterprise Architecture",    company: "Centrix Healthcare Systems" },
  { name: "James Whitfield",    title: "Chief Operating Officer",        company: "NorthStar Energy" },
  { name: "Amara Diallo",       title: "Director of IT Infrastructure",  company: "Quantum Retail Holdings" },
  { name: "Liam O'Brien",       title: "Chief Data Officer",             company: "Ironclad Manufacturing" },
  { name: "Mei Lin",            title: "VP Product Engineering",         company: "HorizonPay Fintech" },
  { name: "Carlos Reyes",       title: "Head of Cloud Strategy",         company: "Aether Aerospace" },
  { name: "Fatima Al-Rashid",   title: "Chief Compliance Officer",       company: "Crescent Capital Bank" },
  { name: "Noah Bergström",     title: "Global Head of Procurement",     company: "Nordvik Automotive" },
  { name: "Isabelle Moreau",    title: "CTO",                            company: "LuxBridge Asset Management" },
  { name: "Kwame Asante",       title: "VP of Security Operations",      company: "Granite Defense Systems" },
  { name: "Yuki Tanaka",        title: "Head of Data Governance",        company: "Nippon Pharma Corp" },
  { name: "Sophia Andriessen",  title: "Chief Digital Officer",          company: "EuroLink Ports Authority" },
  { name: "Ryan Holloway",      title: "SVP Information Technology",     company: "Cascade Media Group" },
  { name: "Aisha Mohammed",     title: "Director of Enterprise Systems", company: "Sahara Trade Alliance" },
  { name: "Ethan Marsh",        title: "Head of Platform Engineering",   company: "Ironwood SaaS" },
  { name: "Valentina Cruz",     title: "Chief Risk Officer",             company: "Pacific Basin Shipping" },
  { name: "Ben Hartley",        title: "VP of IT Architecture",          company: "Bridgepoint Investment Bank" },
  { name: "Zara Osei",          title: "Head of AI & Automation",        company: "Momentum Retail Chain" },
  { name: "Thomas Lindqvist",   title: "Chief Operating Officer",        company: "Vega Industrial Group" },
  { name: "Nadia Kowalski",     title: "SVP Technology",                 company: "BalticCross Healthcare" },
  { name: "Omar Shaikh",        title: "Director, Cloud & DevOps",       company: "FinWave Capital Markets" },
  { name: "Charlotte Dupont",   title: "Head of Enterprise Data",        company: "Renard Luxury Group" },
  { name: "Kevin Tran",         title: "Chief Technology Officer",       company: "BluePath Logistics Tech" },
  { name: "Adaeze Eze",         title: "VP of Business Intelligence",    company: "Pan-Africa Holdings" },
  { name: "Lucas Ferraro",      title: "Global IT Director",             company: "Meridio Automotive" },
  { name: "Hannah Brauer",      title: "Head of Cybersecurity",          company: "Rhine Valley Insurance" },
  { name: "Javier Salinas",     title: "Chief Information Officer",      company: "Tierra Energy Partners" },
  { name: "Anya Petrov",        title: "SVP Digital Operations",         company: "EastWest Trading Corp" },
  { name: "David Mensah",       title: "Director of Cloud Infrastructure","company": "Pinnacle Telecom" },
  { name: "Chloe Nakamura",     title: "Head of Enterprise Architecture","company": "ShieldNet Cybersecurity" },
  { name: "Aleksei Volkov",     title: "VP of Platform Services",        company: "Siberian Resources Corp" },
  { name: "Ingrid Svensson",    title: "Chief Operating Officer",        company: "Nordic Grid Energy" },
  { name: "Tariq Hassan",       title: "Head of IT Governance",          company: "Gulf Capital Partners" },
  { name: "Renata Lima",        title: "Chief Data & Analytics Officer", company: "AmaTech Group Brazil" },
  { name: "Patrick Okonkwo",    title: "SVP Enterprise Technology",      company: "Lagos Port Authority" },
  { name: "Simone Beaumont",    title: "Director, Digital Strategy",     company: "Palais Retail France" },
  { name: "Adrian Korhonen",    title: "CTO",                            company: "Fennica Software" },
  { name: "Leila Ahmadi",       title: "VP Information Security",        company: "TehranAir Holdings" },
  { name: "Marcus Johansson",   title: "Head of Systems Integration",    company: "Skansen Industrial AB" },
  { name: "Danielle Tremblay",  title: "Chief Transformation Officer",   company: "Boreal Energy Canada" },
  { name: "Emeka Obi",          title: "Director of Data Platforms",     company: "NigerDelta Corp" },
  { name: "Sofia Papadopoulos", title: "VP Technology Operations",       company: "Aegean Maritime Group" },
  { name: "William Crane",      title: "Chief Digital Officer",          company: "Irongate Capital US" },
  { name: "Hana Yoshida",       title: "SVP Enterprise Solutions",       company: "Sunrise Electronics" },
  { name: "Mohammed Al-Farsi",  title: "Head of Smart Infrastructure",   company: "Al Noor Development" },
  { name: "Beatriz Santos",     title: "Chief Technology Officer",       company: "Lisbona FinServ" },
];
